# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.18
    working_directory: ~/repo

    steps:
      - checkout
      - add_ssh_keys

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
          
      - run : sudo apt install zip -y

      - run : zip -r final.zip *
          
      - run:
          name: upload files
          command: |
            ssh-keyscan -H 13.229.132.103 >> ~/.ssh/known_hosts
            scp -r ~/repo/final.zip ubuntu@13.229.132.103:/var/www/html
            ls -la
      - run:
          name: run node app
          command: |
            ssh ubuntu@13.229.132.103 "cd /var/www/html && mkdir final && unzip final.zip -d final && sudo pm2 start index.js && sudo pm2 list"
